cds-snc/ai-answers

terragrunt/.checkov.yml, terragrunt/Makefile
Creating the project structure.
=> Create project structure

.github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_staging.yml
Fix up the name of the role so that we can run plan and apply.
=> Fix the name of the role

.github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/database/documentdb.tf, terragrunt/aws/database/inputs.tf, terragrunt/aws/database/outputs.tf, terragrunt/aws/ssm/outputs.tf, terragrunt/env/staging/database/.terraform.lock.hcl, terragrunt/env/staging/database/terragrunt.hcl
Adding terraform code for the document db database.
=> Document DB 

terragrunt/aws/ecs/ecs.tf, terragrunt/aws/ecs/inputs.tf, terragrunt/env/staging/ecs/terragrunt.hcl
Fixing ecs input/output variables for the ecs apply to work.
=> Fixing output/input variables for ecs

terragrunt/aws/ecs/ecs.tf, terragrunt/aws/ecs/inputs.tf, terragrunt/aws/iam/outputs.tf, terragrunt/env/staging/ecs/terragrunt.hcl
Another fix to make ecs apply work.
=> Another fix for ecs apply to work  

terragrunt/aws/ecs/ecs.tf
Another fix for ecs to create the log group first.
=> Create the log group first

.github/workflows/build_and_deploy_staging.yml
Adding a build and deploy action to push the container to the registry for AI answers.
=> Add build and deploy action to AI answers

.github/workflows/build_and_deploy_staging.yml
Forgot to add the ECR login step in my previous PR. This fixes it.
=> Adding ECR login to workflow

.github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_staging.yml, terragrunt/aws/database/documentdb.tf, terragrunt/aws/database/outputs.tf, terragrunt/aws/iam/iam.tf, terragrunt/aws/iam/inputs.tf, terragrunt/aws/ssm/inputs.tf, terragrunt/aws/ssm/outputs.tf, terragrunt/aws/ssm/ssm.tf, terragrunt/env/staging/ecs/terragrunt.hcl, terragrunt/env/staging/iam/terragrunt.hcl
Fixing the DocumentDB value to be generated from the documentdb database and stored in a ssm parameter.
=> Fixing documentdb uri value

.github/workflows/tf_apply_staging.yml, .github/workflows/tf_plan_staging.yml, agents/AgentService.js, api/openai-batch-cancel.js, api/openai-batch-context.js, api/openai-batch-process-results.js, api/openai-batch-status.js, api/openai-batch.js, api/openai-context.js, api/openai-message.js, config/ai-models.js, server/server.js, terragrunt/aws/ecs/ecs.tf, terragrunt/aws/ecs/inputs.tf, terragrunt/aws/ssm/inputs.tf, terragrunt/aws/ssm/outputs.tf, terragrunt/aws/ssm/ssm.tf, terragrunt/env/staging/ecs/terragrunt.hcl, terragrunt/env/staging/iam/terragrunt.hcl
I have updated the code to use the appropriate libraries needed to utilize the new Azure OPENAI Key
=> Use Azure Open AI

terragrunt/aws/ecs/inputs.tf, terragrunt/aws/ecs/security_group.tf, terragrunt/env/staging/ecs/terragrunt.hcl
Removing the initial deletion of ingress rules as this was messing with the security group creation.
=> Fixing ECS security group 

.github/workflows/tf_plan_staging.yml, terragrunt/aws/ecs/security_group.tf
Remove egress rule as it is not necessary.
=> Remove egress rule

terragrunt/aws/ecs/security_group.tf
Removing the egress empty rule.
=> Removing the egress empty rule

terragrunt/aws/ecs/inputs.tf, terragrunt/aws/ecs/security_group.tf
Testing if the security group gets messed up as we fixed a bug with the security group and conftest.
=> Testing security rules

config/ai-models.js, test/test.json
=> fix: remove trailing whitespace in user role definition in test.json

api/db/db-persist-interaction.js
=> fix: update embedding creation to include selected AI provider

src/components/chat/ChatAppContainer.js
=> fix: update default AI provider from OpenAI to Azure

config/ai-models.js
fix: poke to infra
---
---
> jouer au détective. Veuillez aussi inclure toutes …
=> fix: Update ai-models.js

README.md, SYSTEM_CARD.md, SYSTEM_CARD_QUICK_REFERENCE.md
Readme was out of date - Gil was looking for system card. 
---
---
> de l’environnement qui ne font pas partie des étapes …
=> fix:update docs add system card

src/components/chat/ChatAppContainer.js, src/services/ChatPipelineService.js
Roll these files back - turns out there are too many complexities for what I thought could be done fairly simply.
---
---
> de …
=> fix: revert emoji-stripping changes from PR #229

README.md, SYSTEM_CARD.md, SYSTEM_CARD_QUICK_REFERENCE.md
More updates to documentation
---
---
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README …
=> fix:revisions

public/index.html, public/robots.txt
block search engines and AI crawlers while this is still experimental 
---
---
> de l’environnement qui ne font pas partie des …
=> fix:block-robots

src/styles/App.css
=> feat: temp fix to margin shenangians

src/pages/DatabasePage.js
Increase limit and decrease min chunk size
=> fix: adjust export chunk sizes for improved performance

api/db/db-database-management.js, src/pages/DatabasePage.js
logging for database debugging
=> feat: add export limit input and logging for database export operations

server/server.js
=> fix: comment out vector service initialization for debugging purposes

api/db/db-chat-logs.js, src/components/admin/ChatLogsDashboard.js, src/components/admin/MetricsDashboard.js, src/locales/en.json, src/locales/fr.json, src/pages/DatabasePage.js, src/services/DataStoreService.js, src/services/MetricsService.js
- Updated chatLogsHandler to support pagination with lastId and limit parameters.
- Added totalCount to the response for chat logs.
- Modified ChatLogsDashboard to fetch logs in chunks and display loading progress.
- Refactored MetricsDashboard to use MetricsService for fetching chat logs and calculating metrics.
- Improved error handling and loading indicators in both dashboards.
- Removed deprecated DataStoreService methods related to chat logs.
- Added new translations for loading indicators in English and French.
---
> problème (« issue ») GitHub ou la fiche Trello, le cas …
=> feat: Enhance chat logs and metrics handling

src/components/admin/ChatLogsDashboard.js, src/components/admin/MetricsDashboard.js, src/services/MetricsService.js
Added defensive logic to stop loading errors of metrics and chat logs
=> feat: Increase log fetch limit to 500 and add 'harmful' metric tracking

src/services/systemPrompt.js
still map cirnac to isc but wasn't finding the files
had to remove the more elegant solution because it couldn't load the modules.
---
--- …
=> fix: revert-to-original

src/services/systemPrompt/agenticBase.js, src/services/systemPrompt/context-ircc/ircc-scenarios.js, src/services/systemPrompt/scenarios-all.js
changes to agenticBase to force call of context to improve follow-on results, changes to ircc scnearios to address trial issues, change to scenarios all for rcmp domain change
---
---
> Étapes consécutives (1., 2., 3., …) qui …
=> fix: follow-on-context-ircc-rcmp

scripts/delete-merged-branches.ps1, src/components/admin/FilterPanel.js
Ensure that current time zone is used in filter panel, but UTC is sent when doing the query.
=> feat: implement branch deletion script for merged branches

src/services/systemPrompt/context-ircc/ircc-scenarios.js
work permit url has been redirected
add example for work visa questions
---
---
> modification. Elles aideront les développeurs à faire des tests sans avoir …
=> fix: update need-permit url

src/components/chat/ChatAppContainer.js, src/services/ChatPipelineService.js
=> fix: improve handling of short user queries in chat pipeline

.github/scripts/create-lambda-function.sh
=> fix: add retry mechanism to prevent Lambda deployment race condition

api/db/db-chat-logs.js
Include the values when filtering on department or referring url
=> fix: enhance chat log retrieval by adding answer and citation lookups

src/components/admin/FilterPanel.js
=> Fix fix: enhance date parsing and validation in FilterPanel component

src/locales/en.json, src/locales/fr.json, src/pages/HomePage.js
Only 2 clicks in 10 days of second phase of sign-in trial. Was not effective so better to just remove it rather than clutter and complicate.
Issue #362 
---
---
> modification. Elles aideront les …
=> fix: remove immigration expando

src/services/ContextService.js
Log the call to the context agent.
=> feat: log context agent call with message payload

src/pages/HomePage.js, src/styles/App.css
=> feat: container fix

src/App.js
fix for database/settings route disappearing
=> arefactor: remove unused auth expiration checker setup

terragrunt/aws/load_balancer/certificate.tf, terragrunt/aws/load_balancer/inputs.tf, terragrunt/aws/load_balancer/load_balancer.tf, terragrunt/aws/load_balancer/route53.tf, terragrunt/env/production/env_vars.hcl, terragrunt/env/production/load_balancer/terragrunt.hcl, terragrunt/env/staging/load_balancer/terragrunt.hcl
Load balancer change and certificates for french urls
=> fix: enhance load balancer configuration for alternate domain support

src/components/chat/ChatAppContainer.js, terragrunt/aws/load_balancer/load_balancer.tf
=> fix: add loading state management to prevent multiple announcements

services/evaluation.worker.js
Each worker needs it's own vectorService.
=> fix: initialize VectorService in worker to ensure proper functionality

api/batch/batch-stats.js, models/batch.js, src/components/batch/BatchList.js, src/components/batch/BatchUpload.js, src/locales/en.json, src/locales/fr.json, src/pages/BatchPage.js, src/services/BatchService.js
Added workflow option to batches. 
Call was failing because param was not supplied.
=> feat: add workflow handling to batch processing and UI components

public/index.html
- Add AA metadata as outlined by PP https://github.com/cds-snc/ai-answers/issues/421
- Remove "research" and "experimental" from metadata
- Auto-formatting occurred, affecting spacing
=> Feat:  adobe analytics

agents/prompts/piiAgentPrompt.js, src/services/RedactionService.js
With revised approach, need to not treat country of citizenship as PII. Too many questions include a question, confusing to block.
> remove references to country 
---
---
> jouer au détective. Veuillez aussi …
=> fix: remove-country-as-PII

api/db/db-auth-logout.js, api/user/user-auth-logout.js, server/server.js, src/components/RoleProtectedRoute.js, src/contexts/AuthContext.js, src/services/AuthService.js, src/services/__tests__/AuthService.test.js
Fixes two bugs, checks the token expiration when viewing a page, if expired signin
When loging out it clears the variables for the session.
=> feat: implement user logout functionality and enhance token management

src/services/systemPrompt/agenticBase.js, src/services/systemPrompt/context-hc-sc/hc-sc-scenarios.js
per HC request re MRL and attempts to encourage download tool use
---
---
> de l’environnement qui ne font pas partie des …
=> fix: mrl and download

api/batch/batch-stats.js, src/components/batch/BatchList.js, src/pages/BatchPage.js, src/services/BatchService.js
Allow for the batch to complete even if failed items.
=> refactor: enhance batch processing statistics handling and logging

agents/prompts/piiAgentPrompt.js, src/services/systemPrompt/citationInstructions.js
ensure citation matches page-language not question-language
---
---
> de l’environnement qui ne font pas partie des étapes …
=> fix: providing citation based on question language

src/services/systemPrompt/context-cra-arc/cra-arc-scenarios.js, src/services/systemPrompt/scenarios-all.js
=> fix: news-add-readme

models/logs.js
Speed up log view by adding index to chatId
=> chore: Update logs schema for improved logging structure and performance
